spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_eventos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

# crea/actualiza tablas
spring.jpa.hibernate.ddl-auto=update

# data.sql despues de Hibernate
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
